anything = input('Digite algo ')
msg = 'Você digitou {}\n'.format(anything)
msg += 'O tipo desse valor é {}\n'.format(type(anything))
msg += 'Ele é um número? {}\n'.format(anything.isnumeric())
msg += 'Ele é alfabético? {}\n'.format(anything.isalpha())
msg += 'Ele é alfanumérico? {}\n'.format(anything.isalnum())
msg += 'Só tem espaço? {}\n'.format(anything.isspace())
msg += 'Está em minúsculas? {}\n'.format(anything.islower())
msg += 'Está em maiúsculas? {}\n'.format(anything.isupper())
msg += 'Está capitalizada? {}'.format(anything.istitle())
print(msg)
